### ISSUE TITLE
CAN WE USE MATHJAX 2.7 URL INTO THIS EDITOR FOR SHOWING EQUATION

### ISSUE THREAD

**Issue by ngcgolf11** [ether/ep_mathjax#10]
Hi Support!,

we want to implement chemistry, physics and other advanced latex equation is there any way through which we can just add the URL of mathjax2.7 like we call mathjax into our application is there any other way thorough which we can also render physics and chemistry equations.

thanks in advance

**Comment by JohnMcLear** [comment]
We use whatever service is available here: https://latex.codecogs.com/

You can ask them here: https://www.codecogs.com/pages/forums/forum_view.php?f=28
