### ISSUE TITLE
Edit formulas

### ISSUE THREAD

**Issue by Leon0402** [ether/ep_mathjax#13]
Hi, 

would it be possible to be able to edit the formulas? I know that it's an image, but perhaps the formular could be saved and when you click on the image the editor will open again?

Thanks!

**Comment by JohnMcLear** [comment]
Can you please be more explicit on what you mean?

I thought when you clicked on the image/formula it did open the edit window to modify the formula?  Is that not working for you?

**Comment by Leon0402** [comment]
Uhm no actually not. 

![image](https://user-images.githubusercontent.com/33933142/101953475-b5a0a900-3bfa-11eb-9777-42f6ccffd8a3.png)

When I click on it, the cursor is inside the formular and it's selected for a short time (like a button press, but nothing happens). 

![image](https://user-images.githubusercontent.com/33933142/101953591-e2ed5700-3bfa-11eb-90d1-5dcb454cfeef.png)

And if I remove the newline after the formualr i.e. line 5 ... I can't even write text anymore after it

![image](https://user-images.githubusercontent.com/33933142/101953654-031d1600-3bfb-11eb-8cd7-5ad1d44c674b.png)

So if I click enter, the formula goes down a line, on delete it goes up a line. If I click arrow right or click at the right, so my cursor is behind/at the end of the formula it jumps back directly. If I press space, this happens: 

![image](https://user-images.githubusercontent.com/33933142/101953825-5becae80-3bfb-11eb-8b2f-03b297a18c32.png)

**Comment by JohnMcLear** [comment]
Heh, whoops, will fix 2mrw..  Apologies.

**Comment by Leon0402** [comment]
No worries! :) 

So this is a real issue and not some misconfiguration? 

Thanks for the fast response! ;)

**Comment by JohnMcLear** [comment]
I recently refactored so prolly broke something.

**Comment by JohnMcLear** [comment]
Pushed a fix.  Enjoy and thanks.

**Comment by Leon0402** [comment]
Awesome! Working perfectly now :-) Thanks a lot
