### ISSUE TITLE
Center Icon 

### ISSUE THREAD

**Issue by Leon0402** [ether/ep_mathjax#14]
Hi, 

would it be possible to center the icon, so it looks consistent to the rest?

![image](https://user-images.githubusercontent.com/33933142/102135834-d6fed080-3e58-11eb-97f6-83f7fc0cdf17.png)

Thanks! :)

**Comment by JohnMcLear** [comment]
![image](https://user-images.githubusercontent.com/220864/102140004-8b4b2780-3e56-11eb-94e1-bb6511291d0c.png)

looks fine to me?

**Comment by Leon0402** [comment]
well that's weird. My icon also doesn't seem to be correct, it's not a pi. Any idea what the cause could be? 

I just checked it in another browser and the issue is the same.

**Comment by JohnMcLear** [comment]
Try use develop branch of Etherpad.

**Comment by Leon0402** [comment]
I'm on the latest commit of the dev branch https://github.com/ether/etherpad-lite/commit/a4e2ea7

**Comment by JohnMcLear** [comment]
Should be fine now, please try an npm version
